server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**
        - id: technical-service
          uri: lb://technical-service
          predicates:
            - Path=/api/v1/technicals/**
        - id: appointment-service
          uri: lb://appointment-service
          predicates:
            - Path=/api/v1/appointments/**
        - id: publication-service
          uri: lb://publication-service
          predicates:
            - Path=/api/v1/publications/**